# Generated by Django 4.2.1 on 2023-07-30 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Buyer",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=100)),
                ("address1", models.CharField(max_length=100)),
                ("address2", models.CharField(max_length=100)),
                ("address3", models.CharField(max_length=100)),
                ("pin", models.CharField(max_length=15)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "pic1",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="uploads"
                    ),
                ),
                ("otp", models.IntegerField(default=-100005)),
            ],
        ),
        migrations.CreateModel(
            name="Checkout",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("total", models.IntegerField()),
                ("final", models.IntegerField()),
                ("shipping", models.IntegerField()),
                (
                    "rppid",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "paymentmode",
                    models.IntegerField(
                        choices=[(0, "COD"), (1, "Netbanking")], default=0
                    ),
                ),
                (
                    "paymentstatus",
                    models.IntegerField(
                        choices=[(0, "Pending"), (1, "Done")], default=0
                    ),
                ),
                (
                    "orderstatus",
                    models.IntegerField(
                        choices=[
                            (0, "Order Placed"),
                            (1, "Ready To Pack"),
                            (2, "Order Packed"),
                            (3, "Ready To Ship"),
                            (4, "Shipped"),
                            (5, "Out for Delivery"),
                            (6, "Delivered"),
                            (7, "Cancelled"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainApp.buyer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=100)),
                ("mobile", models.CharField(max_length=10)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.CharField(max_length=500)),
                ("date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Maincategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=30)),
                ("size", models.CharField(max_length=30)),
                (
                    "stock",
                    models.CharField(default="In Stock", max_length=30, null=True),
                ),
                ("description", models.CharField(max_length=50)),
                ("baseprice", models.IntegerField()),
                ("discount", models.IntegerField(blank=True, default=0, null=True)),
                ("finalprice", models.IntegerField()),
                (
                    "pic1",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="uploads"
                    ),
                ),
                (
                    "pic2",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="uploads"
                    ),
                ),
                (
                    "pic3",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="uploads"
                    ),
                ),
                (
                    "pic4",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="uploads"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainApp.brand"
                    ),
                ),
                (
                    "maincategory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.maincategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subcategory",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainApp.buyer"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mainApp.subcategory"
            ),
        ),
        migrations.CreateModel(
            name="CheckoutProducts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("qty", models.IntegerField(default=1)),
                ("total", models.IntegerField()),
                (
                    "checkout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.checkout",
                    ),
                ),
                (
                    "p",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.product",
                    ),
                ),
            ],
        ),
    ]
